### ISSUE TITLE
Rails 4.2.0.beta1 throws: can't modify frozen ActiveSupport::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by afair** [FooBarWidget/default_value_for#38]
First, thanks for a great and useful gem. :-)

After trying to test against Rails 4.2.0.beta1 with default_values_for version 3.0.0.1, I get this error:

RuntimeError: can't modify frozen ActiveSupport::HashWithIndifferentAccess
from /Users/allen/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/hash_with_indifferent_access.rb:226:in `delete'

in default_value_for-3.0.0.1/lib/default_value_for.rb:169:in `block in set_default_values'
    changed_attributes.delete(attribute)
is now causing the Exception. I suspect ActiveRecord/Support is now providing a "frozen" hash to work with.

When I remove the default_values_for declaration from the model, I am able to instantiate the object.

POTENTIAL SOLUTION: (Needs more thought and testing)

```
def set_default_values
  @changed_attr ||= Hash.new { |h,k| h[k] = changed_attributes[k] }
  # ...
  @changed_attr.delete(attribute)
   #...
end
```

(This made model instantiation work, but I don't know what it breaks elsewhere)

STACK TRACE:

0: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/hash_with_indifferent_access.rb:226:in `delete'
 1: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/hash_with_indifferent_access.rb:226:in`delete'
 2: /Users/allen/.rvm/gems/ruby-2.1.2/gems/default_value_for-3.0.0.1/lib/default_value_for.rb:169:in `block in set_default_values'
 3: /Users/allen/.rvm/gems/ruby-2.1.2/gems/default_value_for-3.0.0.1/lib/default_value_for.rb:152:in`each'
 4: /Users/allen/.rvm/gems/ruby-2.1.2/gems/default_value_for-3.0.0.1/lib/default_value_for.rb:152:in `set_default_values'
 5: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/callbacks.rb:424:in`block in make_lambda'
 6: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/callbacks.rb:222:in `call'
 7: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/callbacks.rb:222:in`block in halting_and_conditional'
 8: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/callbacks.rb:87:in `call'
 9: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/callbacks.rb:87:in`run_callbacks'
10: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/core.rb:267:in `initialize'
11: /Users/allen/.rvm/gems/ruby-2.1.2/gems/default_value_for-3.0.0.1/lib/default_value_for.rb:142:in`initialize'
12: /Users/allen/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/inheritance.rb:61:in `new'

**Comment by dongennl** [comment]
I'm still getting this in 5.0.0 rc1; app is fine without the gem; ruby 2.2.2p95, even using master branch.

Am I missing something?
