### ISSUE TITLE
`method_missing': undefined method `default_value_for'...

### ISSUE THREAD

**Issue by ryanwjackson** [FooBarWidget/default_value_for#51]
I was super psyched to find this gem, but I can't get it to work.  I have gem `"default_value_for", "~> 3.0.0"` in my Gemfile, and after `bundle install` I get `'method_missing': undefined method `default_value_for'` when starting `rails c`.

Have you seen this before?  The line it is erroring on is `default_value_for :default_billing_cycle_day, 1`

Thanks!

**Comment by norman** [comment]
Did you restart the Rails application?

**Comment by ryanwjackson** [comment]
Yes.  Many times. :)


—
Ryan Jackson

**Comment by norman** [comment]
What version of Rails? If it's 4.2 please make sure you're using default_value_for 3.0.1, since 3.0.0 does not work properly on Rails 4.2. Please also make sure you stop the Rails app fully, including `spring stop`  to be completely sure the gem is loaded in your app.

If none of this works, please let me know if you've done anything else that might affect the way gems are loaded in your application. It's unusual that that method would not be defined in ActiveRecord::Base, since that's the core functionality of the library that runs at startup.

**Comment by ryanwjackson** [comment]
OK, I've narrowed it down a bit.  Here are the details.

I see version 3.0.1 in my `Gemfile.lock`.  And I’m using rails Rails 3.2.17.  I definitely killed everything and started it again.  There is one complication in that I am using a private gem to share models across a couple applications (API server, web server, etc.).  But I have one model (my User model) living on the server where it is erroring out.  

When used on the User model (with `gem "default_value_for", "~> 3.0.0"` in that app's Gemfile, it works fine.  But then when trying to use it in one of the shared models, it throws that error.  But I have `gem "default_value_for", "~> 3.0.0"` in the gem's Gemfile and see the dependency in the gemspec.

It's smelling like more my inability to develop gems (#likely), but any help would be appreciated.

**Comment by norman** [comment]
Ok, closing this issue then - please investigate some more on your own and if you can isolate it to something specific that might be a problem with this gem I'll be happy to reopen.

**Comment by norman** [comment]
Oh, one thing I can recommend you try in your gem that contains your models, is to make sure the DefaultValueFor::ClassMethods module is included in ActiveRecord::Base; Rails does this as a part of its startup process, but your gem may be getting loaded before Rails has started up. Something like this in your gem may help:

```ruby
require 'activerecord'
ActiveRecord::Base.extend DefaultValueFor::ClassMethods
```

**Comment by ryanwjackson** [comment]
Minus the require, it worked swimmingly!  Thanks!!!


—
Ryan Jackson

**Comment by norman** [comment]
Glad to hear it! Thanks for the followup.
