### ISSUE TITLE
Doesn't work with rails 6

### ISSUE THREAD

**Issue by mayordwells** [FooBarWidget/default_value_for#82]
Can you please confirm this gem works in a rails 6.0.0 application? 

It didn't work in mine. It was working fine in Rails 6.0.0.rc2 but not in 6.0.0

**Comment by chrisarcand** [comment]
Hi! The gemspec itself is always set to `< major release of Rails`, which allows you to try out any release candidates but not guarantee official compatibility with the actual release once it ships until verified.

I've started a branch and almost completed work. Thanks for your patience.
