### ISSUE TITLE
Support for Rails 6.1.0

### ISSUE THREAD

**Issue by kapso** [FooBarWidget/default_value_for#87]

**Comment by rew-ron** [comment]
+1

**Comment by fernandoluizao** [comment]
Seems that its just need to relax activerecord dependency in gemspec. Working fine with rails 6.1.

**Comment by KevSlashNull** [comment]
There already appears to be support of 6.1 as of 554563e5277504c286e5e00ce30bd1bd8c9de1f5, #91 adds support for rails 7.0.

**Comment by kbrock** [comment]
This was added in https://github.com/FooBarWidget/default_value_for/pull/89

@kapso could you close this?
